修改 rules/node 中已被 eslint 废弃的 node rules，引入 eslint-plugin-node 及自定规则
eggjs/eslint-config-egg pull request #57
Opened 2020-11-06 06:58 UTC by zhaoxingyue

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

修改后的 node rule 会对不符合 lint 规则的代码报错或 warning 提示

##### Description of change

Fixes #4516

- 引入 [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node)
- 自定义规则
  - 开启 no-new-require rule
  - 开启 prefer-promises rule
  - 开启 prefer-global rule
- 增加单测

2020-11-06 07:34 UTC, whxaxes approved these changes

2020-11-06 07:41 UTC, whxaxes commented
@atian25 @popomore  也看一下？

2020-11-11 06:38 UTC, popomore commented
尽量减少 prefer-global，我觉得保留 console 和 process 是可以的，其他也不是非常常用，没必要 global。

2020-11-11 06:38 UTC, popomore requested changes
这个要发 major 了

2020-11-11 06:44 UTC, zhaoxingyue commented
> 尽量减少 prefer-global，我觉得保留 console 和 process 是可以的，其他也不是非常常用，没必要 global。

其他的用 warn 或者直接关闭？ prefer-global 这个是不是都 follow 一套规则会好一点

2020-11-11 10:59 UTC, popomore approved these changes

2020-11-11 10:59 UTC, merged

2020-11-11 11:01 UTC, popomore commented
+ eslint-config-egg@9.0.0